### ISSUE TITLE
Add documentation to readthedocs.org 

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#101]
Read the Docs hosts documentation, making it fully searchable and easy to find. 
It requires a few changes to the project setup to allow the ReadTheDocs webhook, http://docs.readthedocs.io/en/latest/webhooks.html

**Comment by bokchan** [comment]
The docs are live on readthedocs.io albeit run managed by @bokchan 
The url for the documentation has the form: `http://libdrizle-redux.readthedocs.io/en/[version]/`

Currently the following versions are available: 

- http://libdrizle-redux.readthedocs.io/en/latest/ [v6.x.x]
- http://libdrizle-redux.readthedocs.io/en/stable/ [v6.0.0]
- http://libdrizle-redux.readthedocs.io/en/v6.0.0/
- http://libdrizle-redux.readthedocs.io/en/v5.6.0/
- http://libdrizle-redux.readthedocs.io/en/v5.5.1/
