### ISSUE TITLE
Connection timeout value is never used

### ISSUE THREAD

**Issue by ben-palmer-sociomantic** [sociomantic/libdrizzle-redux#109]
From my initial investigation the libdrizzle-redux connection timeout is never used. It is set using the `drizzle_set_timeout` function (https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/ec0f61b255d0cddb123c368f429d80b6cbf7646f/libdrizzle/drizzle.cc#L151) but it is never actually used.

Instead the `DRIZZLE_DEFAULT_SOCKET_TIMEOUT` which defaults to 10 seconds is always used in the connection code (https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/ec0f61b255d0cddb123c368f429d80b6cbf7646f/libdrizzle/conn.cc#L1527).

**Comment by andreas-bok-sociomantic** [comment]
Ah yes, 
the `timeout` value is used when doing the poll, 
https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/ec0f61b255d0cddb123c368f429d80b6cbf7646f/libdrizzle/drizzle.cc#L336

But not the `waittime` for the socket connection. 
I might add that as an option on the drizzle struct

**Comment by ben-palmer-sociomantic** [comment]
Looking at this a bit more there are a couple of other points:
1) The call to `drizzle_wait` only happens when we are not using non-blocking mode right?
2) So we have two different timeouts here. Currently the timeout is setting the poll timeout but the documentation is claiming that it is setting a socket level IO (https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/c07059be4eb5027c593391848165141c4ef4a655/libdrizzle-5.1/drizzle.h#L131) and the socket level IO is actually set to `DRIZZLE_DEFAULT_SOCKET_TIMEOUT`.

**Comment by andreas-bok-sociomantic** [comment]
> The call to drizzle_wait only happens when we are not using non-blocking mode right?
Yes 

> Currently the timeout is setting the poll timeout but the documentation is claiming that it is setting a socket level IO

Yes that is definitely inconsistent and should be fixed IMO. Should the poll and socket timeouts be be separate config values?
