### ISSUE TITLE
Add jenkins build-script for libdrizzle-redux

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#12]
`libdrizzle-redux` should be added to `jenkins`, so the library is installed for projects using the library

An target for building an `RPM`  package in the **Makefile target** but none building a `deb package`. 
However `RPM` target fails due to missing dependencies. 

What steps are necessary to add a build-script for `libdrizzle-redux` to `jenkins`

Input would be appreciated, @leandro-lucarella-sociomantic, @ben-palmer-sociomantic

**Comment by nemanja-boric-sociomantic** [comment]
> @nemanja-boric-sociomantic mentioned that makd doesn't support compiling C/C++ code
Is that the case?

It wouldn't magically help here, as IIRC it has no idea how to create deb package out of box, look into tango repo, it's just calling build script I think.

**Comment by nemanja-boric-sociomantic** [comment]
https://wiki.debian.org/IntroDebianPackaging might be helpful
