### ISSUE TITLE
Check for error packets while doing handshake

### ISSUE THREAD

**Issue by mathias-baumann-sociomantic** [sociomantic/libdrizzle-redux#120]
It is possible to receive an error packet when doing the handshake, however the code doesn't check for that.

The check needs to be added here:
https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/42d7a60183dd2eb6ec9033447353ef36882e480b/libdrizzle/handshake.cc#L101

There already is code doing such checks for packets arriving after the handshake, found here:
https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/c07059be4eb5027c593391848165141c4ef4a655/libdrizzle/result.cc#L467-L481

See also the definition of the error packet here:
https://dev.mysql.com/doc/internals/en/packet-ERR_Packet.html

And just for anecdotal information, I found & fixed exactly the same buck in mysql-native: https://github.com/mysql-d/mysql-native/issues/20

**Comment by andreas-bok-sociomantic** [comment]
Fixed by #121
