### ISSUE TITLE
Trying to understand a piece of your code

### ISSUE THREAD

**Issue by ruipacheco** [sociomantic/libdrizzle-redux#198]
I'm going through the specs for the wire protocol for MariaDB, as the docs for MySQL seem to be gone, and found this tidbit about flagging null fields in the wire protocol: 

> The NULL-Bitmap indicates if a parameter for a column is null (one bit per parameter) beginning with the 3rd bit. NULL-bitmap size is (number_of_columns + 9) / 8.

https://mariadb.com/kb/en/mariadb/resultset-row/#NULL-Bitmap-values

But I don't think this matches your code: https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/8ae0bfe15e2264378b2c27e275b1c698e9fce546/libdrizzle/statement.cc#L431

How do you check if a column is null or not? I'm trying to understand that particular line of code.

**Comment by mathias-baumann-sociomantic** [comment]
Mind you, we only took over this code from the previous authors and are maintaining / extending it.

About your particular question, what exactly do you think doesn't match in that line?

`if (stmt->execute_result->null_bitmap[(column_counter+2)/8] & (1 << ((column_counter+2) % 8)))`

If we deconstruct this to the basics:

`null_bitmap[(column_counter+2)/8] & (1 << ((column_counter+2) % 8))`

So we're ANDing two values here. If we assume `column_counter = 0` for the first column, we have the values

`null_bitmap[2/8] == null_bitmap[0]` and `(1 << (2%8)) == 1 << 2 == 0b100 // binary representation`

So we check if in the first byte of `null_bitmap` the third bit is set (the docu says "beginning with the 3rd bit") for the first column.

Doing the same with the assumption `column_counter = 1`:

`null_bitmap[3/8] == null_bitmap[0]` and `(1 << (3%8)) == 1 << 3 == 0b1000 // binary representation`

So now we check for the fourth bit of the first byte.
Now, if we go over that first byte, e.g. by assuming `column_count = 10`:

`null_bitmap[10/8] == null_bitmap[1]` and `(1 << (10%8)) == 1 << 2 == 0b100 // binary representation`

This time we check the second bit of the second byte of the null_bitmap... 

It all seems okay to me so far?

**Comment by ruipacheco** [comment]
You're correct, this does make sense. I'm sorry for the confusion.

**Comment by andreas-bok-sociomantic** [comment]
Hi @ruipacheco 

I will have to look into the code a bit more.  

> ...the docs for MySQL seem to be gone, 

Yeah, though it seems they are moving to doxygen generated docs but only for the latest development version...quite annoying: https://dev.mysql.com/doc/dev/mysql-server/latest/

> The NULL-Bitmap indicates if a parameter for a column is null (one bit per parameter) beginning with the 3rd bit. NULL-bitmap size is (number_of_columns + 9) / 8.

AFAICS the null_bitmap is set in the function [`drizzle_state_binary_null_read`](https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/v5.x.x/libdrizzle/field.cc?utf8=✓#L376)

The `execute_result` is of type `drizzle_result_st` which means that it has the `null_bitmap` as well and assigned in the line referred above. 
Thus the check for whether a column is `null` is correct `n'th column + 2` 

```cpp
if (stmt->execute_result->null_bitmap[(column_counter+2)/8] & (1 << ((column_counter+2) % 8)))
```

I did a small example which shows the logic: 
https://code.hackerearth.com/d74366a?key=d31f8473f4932a74cc21b303cb30e9bb

**Comment by andreas-bok-sociomantic** [comment]
@mathias-baumann-sociomantic damn you, was too slow :)

**Comment by ruipacheco** [comment]
> I will have to look into the code a bit more.

I do believe this is correct so no need to waste any more time. I think the MariaDB docs are a bit too terse and I'd had problems with the documentation for the wire protocol being wrong before (which I flagged and they changed). And since MySQL seems to be moving to the X protocol (documentation first, it seems) I was thrown off.

Thanks for all the help!

**Comment by andreas-bok-sociomantic** [comment]
@ruipacheco you are welcome. Btw is it working for you on OSX? Remember you reported an issue a while back

**Comment by ruipacheco** [comment]
It builds fine, so I'd say all is good. Thanks for asking!

**Comment by andreas-bok-sociomantic** [comment]
> It builds fine, so I'd say all is good. Thanks for asking!

Happy to hear :)
