### ISSUE TITLE
Merging original development branches

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#2]
There are two development branches at the libdrizzle redux repos which might be worth merging into our fork. 
I have made efforts to add parsing of binlog events in dive. However it seems better and cleaner to have libdrizzle parse the binlog event data and let the D code call this API. 

@leandro-lucarella-sociomantic , @mathias-baumann-sociomantic , @ben-palmer-sociomantic 

**1 - Compiler fixes**
https://code.launchpad.net/~linuxjedi/libdrizzle/5.1-compiler-fixes/+merge/162339

> The address sanitizer cannot be used at the same time as the thread sanitizer. CLang actually enforces this but for some reason GCC doesn't.
> 
> When both are tried together the address sanitizer barfs on the thread sanitizer lib, I suspect this is due to the way it has to be linked.
> 
> The address sanitizer is probably more useful to libdrizzle right now so disabling the thread sanitizer.

**2 - Extending the api to read binlog event data** 
https://code.launchpad.net/~2591kuldeep/libdrizzle/libdrizzle-binlogapi/+merge/180569 

> Currently only have api to read header for MySQL binlog events. I have built the extended api to read event data also. (libdrizzle/binlogevent)

**Comment by ben-palmer-sociomantic** [comment]
I am not sure I really understand what 1) is for but 2) looks like it is something that would be useful to have.

**Comment by andreas-bok-sociomantic** [comment]
Also reckon that 1) is of less importance, but 2) could be worth looking into.

**Comment by andreas-bok-sociomantic** [comment]
I tried testing with the branch containing binlog eventdata parsing  https://code.launchpad.net/~2591kuldeep/libdrizzle/libdrizzle-binlogapi/+merge/180569 

However it doesn't read the eventdata correctly, at least not with the supplied [example](http://bazaar.launchpad.net/~2591kuldeep/libdrizzle/libdrizzle-binlogapi/view/head:/docs/examples/binlog-read-api.rst)

In spite of this, the modelling of **Row Based Replication** eventdata is complete and could therefore still be of use if we decided to work on adding parsing of binlog eventdata to `libdrizzle redux`

**Comment by andreas-bok-sociomantic** [comment]
This issue was resolved with release [v5.3.0](https://github.com/sociomantic-tsunami/libdrizzle-redux/releases/tag/v5.3.0)
