### ISSUE TITLE
Off-by-one error in drizzle_check_unpack_error()?

### ISSUE THREAD

**Issue by kengruven** [sociomantic/libdrizzle-redux#214]
When I run MySQL's command-line client with a fake schema name, it reports the error like this:

    $ mysql -uroot badname
    ERROR 1049 (42000): Unknown database 'badname'

When I try to connect using libdrizzle-redux:

        conn = drizzle_create("localhost", 3306, "root", "", "badname", nil)
        ok = drizzle_connect(conn)

the C string I get from `drizzle_error(conn)` is:

    "drizzle_check_unpack_error: Unknown database 'badname"

There's no ending `'` here.  When I stop the debugger inside drizzle_check_unpack_error(), I can see:

    con->error_code = (uint16_t) 1049
    con->sqlstate = (char [6]) "42000"
    con->buffer_ptr = (unsigned char *) "Unknown database 'badname't"
    con->last_error = (char [2048]) "Unknown database 'badname"

It looks like it's receiving the full message, but the snprintf call is stopping one byte too early.  There is a fixed size limit of DRIZZLE_MAX_SQLSTATE_SIZE (2048) but this message is well below that (26).

I see the same issue (final character missing) for other error messages, too.

**Comment by andreas-bok-sociomantic** [comment]
Reproduced the error and made a PR for a bugfix, #215
Thanks for reporting the bug :)

**Comment by kengruven** [comment]
Great -- that was quick!  Thanks.

A couple remarks on error handling (which aren't bugs, really):

 - I think it would be handy to have just the server error available as a string, somehow, without the "drizzle_" function name.  It's nicer to present to users than raw MySQL error codes, and drizzle function names aren't useful to (application) users.  (I'm not sure why the drizzle function name is useful to me, even as a developer.  I know what call it was: the one I just made.)

 - There's 2 places that hardcode a function name to drizzle_set_error, rather than using `__func__`: libdrizzle/result.cc:363 and libdrizzle/row.cc:67.
