### ISSUE TITLE
Support CI tests using docker-compose

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#228]
Currently **travis** CI builds run on the native build environment which based on based on **ubuntu trusty**. 
To support build environments on newer versions of **ubuntu** the CI builds are required to run in a docker container. 
One approach is using docker-compose to set up two containers, one running **MySQL** container and another one running the build environment. 

A preliminary implementation is under development is my dev branch, https://github.com/andreas-bok-sociomantic/libdrizzle-redux/tree/use-docker-compose-for-ci, in commits 6022a5cef7d1aa020976d93e7d6992aac5600078..75ecb51877b5a1474a15ba39d0cf67896ed467e3

There are still a few issues to be addressed
- The unittest for connections using socket fails. 
- Configuration of `docker-compose.yaml` files and `Dockerfile` to easily configure different build environments, e.g. RPM build on **centos7**  

FYI @leandro-lucarella-sociomantic

**Comment by leandro-lucarella-sociomantic** [comment]
Ideally we should add support for `docker-compose` to beaver directly, but I think it's fine to start with a custom solution to get some feeling of what's needed.

That said, libdrizzle-redux is not the best project to start with because the build is so complex. I really get lost in the hundreds of LOC.

**Comment by andreas-bok-sociomantic** [comment]
Oki. Next I will look into doing all Linux builds in docker, i.e with different compiler versions and rpm package  build in centos. Furthermore considering adding conditional builds for osx. Travis isn't really stable enough for those builds.

**Comment by andreas-bok-sociomantic** [comment]
FYI @leandro-lucarella-sociomantic, The implementation now uses `docker-compose` for all linux based builds on `travis`. 
Deployment to `bintray` is done as before, but with the deb packages generated in the docker-container. 

https://github.com/andreas-bok-sociomantic/libdrizzle-redux/tree/use-docker-compose-for-ci

**Comment by andreas-bok-sociomantic** [comment]
@leandro-lucarella-sociomantic do you reckon this change is ready to go PR. It would allow the libdrizzle-redux build to be removed from jenkins.

**Comment by leandro-lucarella-sociomantic** [comment]
I think to evaluate that is better to do a PR, otherwise is hard to see what changes and make comments.

**Comment by andreas-bok-sociomantic** [comment]
> I think to evaluate that is better to do a PR, otherwise is hard to see what changes and make comments.

Created a **WIP** PR, #238

**Comment by andreas-bok-sociomantic** [comment]
Addresed by #238
