### ISSUE TITLE
Remove Trusty support

### ISSUE THREAD

**Issue by leandro-lucarella-sociomantic** [sociomantic/libdrizzle-redux#239]
Remove trusty support from all projects. Trusty is already more than 3 years old and the latest LTS (Xenial) has already been out there for more than a year, so it should be enough to maintain the latest LTS only now.

**Comment by leandro-lucarella-sociomantic** [comment]
I tried to have a look at this but I don't understand the build system here, is too complex, I can't even find for which distro is this built. I guess is not using docker so it's built in the trusty travis env directly?

Can you take care of this @andreas-bok-sociomantic at some point (ideally not too far in the future, but not super high-prio).

**Comment by andreas-bok-sociomantic** [comment]
Can you take care of this @andreas-bok-sociomantic at some point (ideally not too far in the future, but not super high-prio).

Sure. 

>  I guess is not using docker so it's built in the trusty travis env directly?

Yes, the PR, #238, to build the project using `docker-compose` at **travis** was created for the purpose of allowing the project to be built on `xenial` and not the native trusty build environment. 
In addition the `xenial` package is deployed to **bintray**. 

So does #238 solve this issue as well?

**Comment by leandro-lucarella-sociomantic** [comment]
Yes, it should. Thanks!

**Comment by andreas-bok-sociomantic** [comment]
Addressed comments from @leandro-lucarella-sociomantic 
- removed overwrite flag `-O` in `travis` **deploy** step
- added note about all `ubuntu` builds are `xenial` only
