### ISSUE TITLE
End of support for minor branches v5.5.x, v5.6.x and v6.0.x*

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#241]
We are planning to change the support guarantees for minor branches to include only the most recent, 
cf.  #233 
@chenzhuoyu AFAIK you are using `libdrizzle-redux` in production, is that correct?
Given your great contributions I won't go ahead with this if that would cause problems for your internal use of the library. 

* v6.1.0 is almost ready to be released, so v6.0.x will of course receive patches until that release

**Comment by andreas-bok-sociomantic** [comment]
ping @chenzhuoyu

**Comment by andreas-bok-sociomantic** [comment]
I will close this due to lack of response.

**Comment by chenzhuoyu** [comment]
Sorry for the late reply, we've already using v6.0.0. Once v6.1.0 is available, we will upgrade our library as soon as possible :) @andreas-bok-sociomantic

**Comment by andreas-bok-sociomantic** [comment]
@chenzhuoyu, super. v6.0.1 is soon gonna be released. Possibly today.
