### ISSUE TITLE
Caching of docker images on travis ci

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#272]
The docker images for `mysql` and `libdrizzle-redux` are downloaded in every build on `travis-ci`
There exist some guides on how to cache the needed docker images and share it between builds. 

- https://giorgos.sealabs.net/docker-cache-on-travis-and-docker-112.html
- http://atodorov.org/blog/2017/08/07/faster-travis-ci-tests-with-docker-cache/

However from an initial implementation, the time to save, upload the saved image to AW3 and load the image exceeds the build time for uncached builds. 

https://github.com/andreas-bok-sociomantic/libdrizzle-redux/tree/cache-docker-images

**Comment by leandro-lucarella-sociomantic** [comment]
Sadly, it doesn't help according to my testing.

* https://github.com/sociomantic-tsunami/ocean/pull/103
* https://github.com/sociomantic-tsunami/ocean/issues/15
