### ISSUE TITLE
Assess merging libdrizzle-redux developement branch 5.2

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#40]
We used the latest stable version of libdrizzle-redux 5.1.4 Felmingham as base for this repository. 

As a question for original authors, @LinuxJedi @BrianAker, @wiml, @Shrews of the library: What is your assessment of the status (stability) of the development branch 5.2 wrt. merging it into this repository? 

I haven't gone through all the revisions but e.g. the commit [**Avoid blocking in drizzle_connect() if the connection is set to nonblocking.**](http://bazaar.launchpad.net/~wiml-omni/libdrizzle/nonblocking/revision/132) is of interest since our usecase is only with non-blocking connections. 

ping @leandro-lucarella-sociomantic, @ben-palmer-sociomantic

**Comment by LinuxJedi** [comment]
I don't actually remember the state of 5.2 at all, or if there was anything there apart from merges from 5.1. I also haven't tested Wim's branches but he is a competent engineer so I suspect it will work.

**Comment by andreas-bok-sociomantic** [comment]
@LinuxJedi, thanks for the reply. 

I took a look at the diff and AFAICS the biggest changes are wrt. the `event_watch_fn` which we added back into the lib and the 5.2 changes in `conn.cc`.

**Comment by andreas-bok-sociomantic** [comment]
Created #41 #42 to address this issue

**Comment by andreas-bok-sociomantic** [comment]
Closing this issue since related PRs have been merged
