### ISSUE TITLE
Add example code for use of set_event_watch_fn

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#54]
The documentation should provide example code for the use of `set_event_watch_fn` which was added (back) in [**libdrizzle v5.2.0**](https://github.com/sociomantic-tsunami/libdrizzle-redux/releases/tag/v5.2.0)

**Comment by ben-palmer-sociomantic** [comment]
Not sure if this is out of scope of this issue but it would be good to add documentation and sample code for the non-blocking binlog stuff as well.
