### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#6]
Continuous integration for the repo should be added

A list of Continous Integration Services is here: 
https://github.com/ligurio/Continuous-Integration-services/blob/master/continuous-integration-services-list.md

Free for opensourcea and with database support: 
[TravisCI](https://travis-ci.org/) 
[SemaphoreCI](https://semaphoreci.com/docs/)

**Comment by leandro-lucarella-sociomantic** [comment]
I've used travis-ci before, and it's OK. You just have to include a `.travis.yml` (or something like that) in the project with the commands you want to run and that's it. Oh! And set up the hooks.

**Comment by andreas-bok-sociomantic** [comment]
Ok, I will go for `travis-ci`. 
Will require a minor change in `bootstrap.sh` since `jenkins` was used for CI in original branch. 
Should the check for the `jenkins` support simply be removed?

**Comment by andreas-bok-sociomantic** [comment]
Should I create an account on travis-ci.org or do we have **sociomantic** account for tsunami projects already?

**Comment by andreas-bok-sociomantic** [comment]
I can't add the repo to travis-ci, as I am not admin on the repo. @leandro-lucarella-sociomantic  Is it better that you add the repo to travis and activate it?

**Comment by leandro-lucarella-sociomantic** [comment]
I guess it would be better for @ben-palmer-sociomantic to do it. But another option would be to make you admin of this repo, as you'll be the one actually doing most of the work. I leave that to Ben.

**Comment by ben-palmer-sociomantic** [comment]
![screenshot from 2015-12-10 11 52 07](https://cloud.githubusercontent.com/assets/2894657/11713605/bf75fe16-9f34-11e5-8cdd-cbf12f663a66.png)

**Comment by ben-palmer-sociomantic** [comment]
@leandro-lucarella-sociomantic this are the requested permissions for the travis ci testing. Is this ok to authorise? I don't see any problems but seeing the organization access made me nervous and I wanted to double check.

**Comment by ben-palmer-sociomantic** [comment]
So after briefly granting access to travis-cl to this repo from my sociomantic account it seems this needs organization access so it would be better to do it from a non sociomantic account so I have reverted the application permissions. See also https://github.com/sociomantic/microbe/issues/67 for microbe. So instead I will grant administrator rights to @bokchan and he can grant the permissions to the application without involving the organization.

**Comment by ben-palmer-sociomantic** [comment]
@leandro-lucarella-sociomantic would you prefer we start a new `external-libdrizzle-redux` team and add @bokchan to it or shall I just add him as an admin collaborator?

**Comment by ben-palmer-sociomantic** [comment]
(just as a note as well this would be worth adding to the open sourcing guidelines to prevent any confusion or more serious granting of application authorization problems - e.g. access to repos)

**Comment by leandro-lucarella-sociomantic** [comment]
Adding him as admin collaborator should be fine.

**Comment by bokchan** [comment]
I now see the libdrizzle-redux when using travis-ci under my private github account.

**Comment by andreas-bok-sociomantic** [comment]
Travis CI now works with the repo, cf. #11

**Comment by andreas-bok-sociomantic** [comment]
Related PR #11
