### ISSUE TITLE
Compile error with clang on osx for long long 

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#62]
```
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
```

Running `./configure` gives the following error

``` sh
-DPIC -o libdrizzle/.libs/libdrizzle_libdrizzle_redux_la-field.o
libdrizzle/field.cc:150:5: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
#if SIZE_MAX < UINT64_MAX
    ^
/usr/include/stdint.h:153:20: note: expanded from macro 'SIZE_MAX'
#define SIZE_MAX          UINT64_MAX
                          ^
/usr/include/stdint.h:87:27: note: expanded from macro 'UINT64_MAX'
#define UINT64_MAX        18446744073709551615ULL
                          ^
libdrizzle/field.cc:150:16: error: 'long long' is a C++11 extension [-Werror,-Wc++11-long-long]
#if SIZE_MAX < UINT64_MAX
               ^
/usr/include/stdint.h:87:27: note: expanded from macro 'UINT64_MAX'
#define UINT64_MAX        18446744073709551615ULL
                          ^
2 errors generated.
make[1]: *** [libdrizzle/libdrizzle_libdrizzle_redux_la-field.lo] Error 1
make: *** [all] Error 2
```

The code in question is : 

``` cxx
libdrizzle/field.cc:150

#if SIZE_MAX < UINT64_MAX
  if (wire_size >= SIZE_MAX)
  {
    drizzle_set_error(result->con, __func__, "Field is larger than memory.");
    *ret_ptr= DRIZZLE_RETURN_MEMORY;
    return NULL;
  }
#endif
```

The origin of the bug seems to be this commit 42823bf941c26c6b3a36f83b4e33abd207e3e57c, after which field sizes and offsets were stored as`uint64_t` 

Possible fixes are: 
1.  Remove `_APPEND_COMPILE_FLAGS_ERROR([-Wlong-long])` from compile flags, i.e. removing this line from [ax_harden_compiler_flags.m4#L205](https://github.com/sociomantic-tsunami/libdrizzle-redux/blob/master/m4/ax_harden_compiler_flags.m4#L205) 
2. If the target platform is darwin and the compiler is clang add `-std=c++11 -stdlib=libc++` to `CXXFLAGS`

**Comment by ruipacheco** [comment]
I tried removing `_APPEND_COMPILE_FLAGS_ERROR([-Wlong-long])` but it didn't work. Where should I add values to `CXXFLAGS`?

**Comment by andreas-bok-sociomantic** [comment]
@ruipacheco I will revisit the issue asap. Stay tuned

**Comment by ruipacheco** [comment]
Just to have an idea, what do you think is your ETA on this?

**Comment by andreas-bok-sociomantic** [comment]
I will say by the end of this week, just to have a bit of slack.

**Comment by ruipacheco** [comment]
Thanks!

**Comment by andreas-bok-sociomantic** [comment]
Just out of curiousity, are you using the library in a project?

**Comment by ruipacheco** [comment]
I'm toying with it for now.

**Comment by ruipacheco** [comment]
Tried implementing this, got the following error:

```
libdrizzle/conn.cc:1652:41: error: use of undeclared identifier 'TCP_KEEPIDLE'
  ret= setsockopt(con->fd, IPPROTO_TCP, TCP_KEEPIDLE,
                                        ^
1 error generated.
gmake[1]: *** [Makefile:1358: libdrizzle/libdrizzle_libdrizzle_redux_la-conn.lo] Error 1
gmake[1]: Leaving directory '/Users/ruihpacheco/Desktop/libdrizzle-redux'
gmake: *** [Makefile:814: all] Error 2
./bootstrap.sh:972: Failed to execute /opt/local/bin/gmake all
```

The library builds fine on Ubuntu (without the `-long-long` fix though).

**Comment by andreas-bok-sociomantic** [comment]
I did a bit of testing as well yesterday. And get the same error. The reason is that OSX doesn't support TCP_KEEPIDLE, TCP_KEEPALIVE and TCP_KEEPINTVL. 
I am working on a patch which will fix that and other issues I detected. 
I will post any progress here.

**Comment by ruipacheco** [comment]
Thanks!

**Comment by andreas-bok-sociomantic** [comment]
@ruipacheco the issues should be fixed. They should all go into v5.5.3. 
If you are very eager to test it out yourself you can merge or rebase your local v5.5.x branch with #156, #158, #159 and #161

**Comment by andreas-bok-sociomantic** [comment]
@ruipacheco the new patch release is with fixes for osx. Happy coding
