### ISSUE TITLE
Review ABI versioning scheme 

### ISSUE THREAD

**Issue by andreas-bok-sociomantic** [sociomantic/libdrizzle-redux#92]
Following the guide in `configure.ac` for bumping the ABI version can lead to binary incompatibility. 
A less error prone versioning scheme should be considered.

**Comment by mathias-lang-sociomantic** [comment]
- Major: Part of the ABI were removed, changed, or some symbol's internal changed behavior in a way which is noticeable from outside
- Minor : New internal symbols are available (the case we had with ssl was a special case here)
- Patch: Bugfixes only

The rule to binary compatibility follows the rule of source compatibility:
- You can go back and forth between patch release without any change required
- You can go forward in minor release without requiring any change to applications
- Any change to the application == major

**Comment by andreas-bok-sociomantic** [comment]
Created a PR to improve the documentation of the ABI versioning, #130
